default = "nyc1"

[[location]]
name = "nyc1"
description = "New York 1"

[[location]]
name = "sgp1"
description = "Singapore 1"

[[location]]
name = "lon1"
description = "London 1"

[[location]]
name = "nyc3"
description = "New York 3"

[[location]]
name = "ams3"
description = "Amsterdam 3"

[[location]]
name = "fra1"
description = "Frankfurt 1"

[[location]]
name = "tor1"
description = "Toronto 1"

[[location]]
name = "sfo2"
description = "San Francisco 2"

[[location]]
name = "blr1"
description = "Bangalore 1"

[[location]]
name = "sfo3"
description = "San Francisco 3"

[[location]]
name = "syd1"
description = "Sydney 1"
